FROM jetbrains/teamcity-agent

# Install nodejs v. 14
# RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN sudo apt install nodejs
RUN node --version
